---
http:
  routers:
    homeassistant:
      rule: "Host(`ha.example.invalid`)"
      entryPoints:
        - websecure
      service: homeassistant
      middlewares:
        - secure-headers
      tls:
        certResolver: letsencrypt
