[Definition]
failregex = ^ *\{.*"ClientHost":"<HOST>".*"RequestPath":"/(\.env(/|$)|\.git(/|$)|wp-admin(/|$)|wp-login\.php(\?|")|phpmyadmin(/|$)|server-status(\?|")).*"DownstreamStatus":(403|404)(,|}).*$
ignoreregex =
