---
vulnerabilities:
  - id: CVE-2026-25681
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-27136
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-27145
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-32597
    paths: [ak-root/.venv/lib/python3.14/site-packages/pyjwt-2.11.0.dist-info/METADATA]
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-33811
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-33814
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-39820
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-39821
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-39822
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-39836
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-42499
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-42504
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-44431
    paths: [ak-root/.venv/lib/python3.14/site-packages/urllib3-2.6.3.dist-info/METADATA]
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-44432
    paths: [ak-root/.venv/lib/python3.14/site-packages/urllib3-2.6.3.dist-info/METADATA]
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: CVE-2026-48526
    paths: [ak-root/.venv/lib/python3.14/site-packages/pyjwt-2.11.0.dist-info/METADATA]
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: GHSA-537c-gmf6-5ccf
    paths: [ak-root/.venv/lib/python3.14/site-packages/cryptography-48.0.0.dist-info/METADATA]
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: GHSA-6v7p-g79w-8964
    paths: [ak-root/.venv/lib/python3.14/site-packages/msgpack-1.1.2.dist-info/METADATA]
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
  - id: GHSA-82j2-j2ch-gfr8
    statement: Temporary upstream image dependency pending an authentik release.
    expired_at: 2026-08-20
