[Definition]
failregex = ^ *\{.*"ClientHost":"<HOST>".*"DownstreamStatus":(403|404)(,|}).*"RequestPath":"/(\.env(/|$)|\.git(/|$)|wp-admin(/|$)|wp-login\.php(\?|")|phpmyadmin(/|$)|server-status(\?|")).*$
ignoreregex =
