---
image: docker.io/library/traefik
version: v3.7.13
digest: sha256:1c32e7c368204fd72812152ebdd2ac0425993df6fd982317deb02e48f2d5423c
package_version: 3.7.13-2
source: https://github.com/traefik/traefik
release_url: https://github.com/traefik/traefik/releases/tag
changelog_template: Update Traefik Proxy to [{upstream_version}]({upstream_link}).
