---
image: docker.io/library/traefik
version: v3.7.12
digest: sha256:5447d0eaf375d832b8f224f88db0e80c0a2d44554fc973e3ba72c3a52946cfcc
package_version: 3.7.12-1
source: https://github.com/traefik/traefik
release_url: https://github.com/traefik/traefik/releases/tag
changelog_template: Update Traefik Proxy to [{upstream_version}]({upstream_link}).
